terryyin/lizard

lizard.py, test/testCAndCPP.py
This fix mainly applies to constructors with initialization lists.
The last member variable name is picked up as the name for reporting.
=> Processing with C++11 'noexcept' keyword

test/testCAndCPP.py
Tests are examples for issue #64.
If a member variable or base class is initialized
with an initializer list or uniform initialization
within the initialization list,
the constructor is parsed as multiple function definition.
=> Add tests for failing constructor C++11 init list

lizard.py, test/testCAndCPP.py
This is a quick and dirty fix.
@terryyin may hack further to find the right way (state, regex?).
=> Hack '~' into C++ destructor names

test/testCAndCPP.py
The name of the class is not attached to the operator overload.
This is an example for #70
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/terryyin/lizard/71)
=> Add a test for inline C++ operator overload

lizard.py, lizard_ext/__init__.py, lizard_ext/ttcn.py, test/testTTCN.py
This adds support for the `TTCN-3` language which is a strongly typed compiled language for conformance testing.
It is imperative and "C-like" with a few special constructs.
In TTCN there is the concept of _testcase_ and _control_ "functions" these special constructs are in lizards output prefixed with `__testcase__` and `__control__` respectively (to be able to distinguish between them and ordinary functions since they are _special_) **please** comment if you want this solved in a any other way.
Sample output:
```
> ~/Development/python-lizard/lizard -V comptest.ttcn
================================================
NLOC    CCN   token  PARAM  length  location  
------------------------------------------------
9      1     71      0       9 createconfig@65-74@comptest.ttcn
3      1     20 …
```
=> TTCN-3 language support

lizard.py, test/testCAndCPP.py
Nesting unnamed namespace adds extra ``::`` to the qualification.
```cpp
namespace real { namespace { void foo(int) {...} } }
```
The function is qualified as ``real::::foo`` instead of just ``real::foo``.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/terryyin/lizard/75)
=> Ignore C++11 unnamed namespace for qualifications

lizard.py, test/testCyclomaticComplexity.py
Consider a simple use case:
```cpp
assert((conditional_expression) && "More description...");
```
This line adds 1 + CCN(conditional_expression)
if the assertion is counted as a part of a function.
Since assertions are mostly used
to check (pre, post)-conditions,
to explicitly state assumptions,
and to catch programmer errors,
they are not expected to be a part of the flow of a function.
Moreover, assertions with side-effects is a very bad idea.
The function should stay the same
if all the assertions are removed (in release mode, for example).
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/terryyin/lizard/79)
=> Exclude code in C/C++ 'assert' from CCN

test/testAssertionExtension.py
This is additional tests for handling C/C++ asserts with an extension #79.
The code should ignore complexity of any code inside assert.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/terryyin/lizard/80)
=> Add test cases for IgnoreAssert extension

lizard.py
In some places, it seems that the results of calculations
are expected to be floats,
but integer division of Python2 is used.
In other places, explicit cast to float is made to get the float result.
Python3 division approach for integers helps cleanup these places
and make them consistent.
If Lizard relies on integer division approach of Python2,
which doesn't seem to be the case,
the code must be corrected with ``//``.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/terryyin/lizard/93)
=> Use Python3 division for calculation of averages

lizard.py, lizard_ext/lizardns.py, test/testNestedStructures.py
The code is refactored to work with nesting level metric
provided by language readers of Lizard.
The feature is only tested with Python and C++.
This implementation should be enough to close #69.
=> Generalize Nested Structure Counting for languages 

lizard_languages/clike.py, lizard_languages/code_reader.py, test/test_languages/testCAndCPP.py
Trailing return types in C++11 functions
are not registering the function.
The current fix just ignores
whatever is in the trailing return.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/terryyin/lizard/146)
=> C++11 function trailing return type

lizard_languages/clike.py, test/testCyclomaticComplexity.py, test/test_languages/testCAndCPP.py
C++11 ref qualifiers participate in overload resolution
for performance optimization code.
A test for similar looking '&&' operator is also added.
Closes #143 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/terryyin/lizard/144)
=> Fix C++11 ref qualifiers for functions

test/test_languages/testCAndCPP.py
The current implementation in Lizard
doesn't recognize these special tokens.
However, the use cases do not affect the complexity metrics,
which is more important than accurate token count.
Originally, Lizard recognized '>>>' token,
but it broke C++11 template code as in PR #68.
The current strategy of ignoring these dialect tokens
seems to be good enough.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/terryyin/lizard/148)
=> Add a test for Nvidia CUDA dialect <<< and >>>

lizard_languages/clike.py, test/test_languages/testCAndCPP.py
The constexpr inside of the noexcept
is messing the parser as a function declaration parentheses.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/terryyin/lizard/147)
=> Fix handling of constexpr in C++11 noexcept

lizard_ext/xmloutput.py, test/testOutput.py
Hi Terry, 
in case when lizard does not find any function in the file or folder it crashes. 
I added a simple condition to check for such scenarios.
Cheers,
Milo
=> Fix error division by zero when running on empty folder.

lizard_languages/clike.py, test/test_languages/testCAndCPP.py
Initial support for C++11 [attributes](http://en.cppreference.com/w/cpp/language/attributes).
There's no need to process them for the current Lizard analyses,
so all attributes are ignored.
If attributes are not processed (ignored),
they mess the class/namespace names and confuse the function processing states.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/terryyin/lizard/156)
=> C++11 Attributes

.travis.yml, README.rst, hfcca, hfcca.bat, lizard, lizard.bat, lizard.py, profile.py, setup.py, test/testApplication.py
The setup configurations
and the entry points to the lizard.py are simplified.
System specific bat files are removed.
The `hfcca` entry point is removed.
The changes may break scripts
that use the deleted entry points.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/terryyin/lizard/161)
=> Refactor setup.py script and the installation

test/testNestedStructures.py
This is Python's language quirk.
AFAIK these structures are only relevant to nested structure counting.
I don't know
if other metrics should ensure accuracy for these constructs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/terryyin/lizard/153)
=> Add tests for Python 'for-else' and 'while-else'

lizard.py, test/testApplication.py
Having trouble with setting high enough ignore for Makefiles?
Set it to infinity!
(infinity being -1 or less)
Call this a pessimistic math.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/terryyin/lizard/167)
=> Add 'ignore any warnings' for the exit code

lizard_ext/lizardns.py, lizard_languages/clike.py, test/testNestedStructures.py
The nesting structure extension
is running before the assignment of the nesting level for tokens.
The solution is to increment the nesting level
right at the end of control-flow structure declaration
but before its body.
In addition,
the token is yielded before being processed by the NS extension
to simulate running the extension after the code reader,
but this is somewhat hacky.
This bug (surprisingly) has been a feature!
The fix broke the gotcha braceless nested if-then-else structures.
As a result, separate handling of these "paired" structures is implemented.
Fixes #157.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/terryyin/lizard/174)
=> Fix handling of braceless consecutive NS structures

.appveyor.yml, Makefile, dev_requirements.txt, setup.cfg, test/testCyclomaticComplexity.py
Pytest is awesome with built-in parametrization and mocking.
An example refactoring of CCN tests is provided.
It removes a lot of boilerplate.
The transition can be gradual since Pytest can run Nose tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/terryyin/lizard/175)
=> Switch from nose to pytest

.gitignore, .idea/vcs.xml, lizard.py, lizard_ext/__init__.py, lizard_ext/csvoutput.py, test/testOutputCSV.py
Pretty much what it says: 
Using "--csv" at the command line (I wasn't able to find a logical one-char short switch), will transform the output into CSV.
The output will be identical in structure to the default output, but with some additions: 
* New tokens for each line
* Less verbosity (will not summarize files, will not highlight those that breached a threshold)
=> Add CSV output transform

README.rst, lizard_ext/csvoutput.py, test/testOutputCSV.py
A new toggle to include/exclude the CSV header, when using the --csv output type. Tests and README updated appropriately.
=> Using "verbose" flag to toggle CSV header

lizard_ext/auto_open.py
Fix warning such as:
`lizard_ext/auto_open.py:31: ResourceWarning: unclosed file`
=> Fix unclosed file warning in auto_open

lizard_languages/swift.py, test/test_languages/testSwift.py
This is an untested attempt to fix #240 by adding a declarative state to ignore variable names like `get` or `set`.
=> adding an _expect_declaration_name state for Swift

lizard.py, lizard_ext/template.html, test/testOutput.py, test/testOutputFile.py
As documented, warnings are generated when metrics (e.g. CCN) are
bigger (>) than the threshold. Thus, we should use the same logic
in the HTML output, and use greater (>) instead of gte (>=).
=> Fixed warning threshold inconsistency in HTML output.

lizard_languages/swift.py, test/test_languages/testSwift.py
This code's ccn is 2.
```swift
guard isValid else { return }
```
This code is equal `if isValid { return }`, so lizard shold output 2.
=> Fixed Issue 267: guard clause is not counted by ccn.

lizard_languages/swift.py, test/test_languages/testSwift.py
This code's ccn is 1.
```swift
something(for: .something)
```
Because I don't know how to scan arrays efficiently in Python, it's an index-based implementation. I would like to point out.
=> Fixed Issue 265: ignore `for` label name by swift.

README.rst
Some links at the end of README.rst were in markdown link format and
therefore rendering incorrectly.  Change them to Restructured Text
format.
=> Fixup README.rst link format.

lizard.py
Including whitespace between tokens in the items of `full_parameters` prevents parameter types in explicitly-typed languages being erroneously appended to the front of parameter names.
=> separate parameter type from identifier

.travis.yml, build.sh, dev_requirements.txt, lizard.py, lizard_ext/version.py
I saw your last build was failing after a pull request #298 from yalechen-cyw/master.
These changes (my mastrer version 1bdf8e2) should give a working build again (I've added a build.sh to work locally and should be safe to ignore.)
Due to my unfamiliarity with travis I needed some commits to get it to work, but the changes in the end are just a few.
Further this is my first pull request so I'm not sure if the patch files get automatically added or if the reference to the working version is included.
* Build failed mainly because one line was too long
* I needed to fix the pygments to version 2.3.1 to have the build on version 3.4 succeed.
* Not sure how you work with the version. I just added a very small increment.
=> Fix the failing build

Makefile, dev_requirements.txt, lizard_ext/__init__.py, lizard_ext/csvoutput.py, lizard_ext/lizardexitcount.py, lizard_ext/lizardgotocount.py, lizard_ext/lizardstatementcount.py, lizard_ext/version.py, test/testFunctionGotoCount.py, test/testFunctionStatementCount.py, test/testOutputCSV.py
Hi,
I've got a new request for you. Included in this request are:
- code coverage measurement of the executed unit tests
- added a few extensions: goto counter and (a rather basic) statement counter (including tests)
- extended the cvsoutput method to include the extensions (extended the tests for this)
- Tried to work away as much warnings as possible.
If you have any comments on my code please let me know.
One question: Is there a special reason why the tests use assertEqual instead of the assertRegex as stated by the DeprecationWarning?
=> Including coverage, extensions goto_count, statement_count and extended cvs output

lizard_ext/htmloutput.py
Hi :wave: 
I noticed that all `Parameter count` columns in generated html files are always `0` as the following image.
This PR fixes the issue.
ref: https://github.com/terryyin/lizard/commit/4a5d8275521fc86e878c3f3f8a82e0e972d7aa3e
=> Fix wrong variable name in html template

README.rst, lizard.py
- Add TypeScript to the list of supported languages
- Update options section in README
- Fix typo in help text
=> Add TypeScript in README

lizard.py, test/testOutput.py, test/testOutputCSV.py
Small simplification of `FunctionInfo`'s `length` in order to not care about it anywhere else during the parsing process.
`int(self.start_line != self.end_line)` only for consistency with equal start and end lines.
=> Make length a property of FileInfo

lizard_languages/python.py, test/test_languages/testPython.py
fix issue #292 
In a multi-line function declaration, if a subsequent line is indented much more than the first line, it will result in the wrong end line of the function.
Example:
```
def foo(arg1,
arg2,
arg3
):
if True:
return
```
=> Fix incorrect python function end line when function declared with multiple lines

lizard.py, lizard_languages/python.py, test/test_languages/testPython.py
Addresses https://github.com/terryyin/lizard/issues/354
In several situations, the argument count reported for python is incorrect. In particular:
- When a trailing comma is included in a function argument list
- When a parameterized type hint is provided that includes commas, e.g. dict[str, tuple[int, float]]
Below is a code snippet that reproduces these issues:
```python
def func_with_trailing_comma(
a,
b,
c,
):
pass
def func_with_type_parameterized_args(a: dict[str, tuple[int, float]]):
pass
```
Running `lizard -a 2 demo.py` on this reports the following:
```
================================================
NLOC    CCN   token  PARAM  length  location  
------------------------------------------------
6      1     11      4       6 func_with_trailing_comma@1-6@demo.py
2      1     18 …
```
=> fix: Correct parameter count for python function with trailing comma and parameterized type hints

lizard_languages/clike.py, test/test_languages/testCAndCPP.py
Fixes #368 
`void` used in a parameter declaration should not lead to the parameter count to increase. Semantically `void` means no parameter in that case.
=> fix: Do not count `void` as a parameter (C/C++)

lizard_languages/golike.py, test/test_languages/testGo.py
=> Fix Golike state machine misinterpretation of func keyword inside Struct and Interface definitions

setup.py
`erlang.py` requires `pygments`, so make it a requirement of the project.
Resolves https://github.com/terryyin/lizard/issues/392
=> require pygments

lizard_languages/rust.py, test/test_languages/testRust.py
Lizard interpreted two `'` signs as a string instead of a lifetime, hence the bug where the function would be omitted.
=> Rust: correctly interpret lifetimes, labels

lizard.py, test/testFilesFilter.py, test/testOutput.py
On Windows systems where the default encoding is not UTF-8 (e.g., Japanese cp932), reading UTF-8 BOM files may fail if the encoding is not explicitly specified in the open() function.
The open() function was called without specifying the encoding, which can lead to failures when reading UTF-8 BOM files on Windows systems with non-UTF-8 defaults like cp932.
- Replaced direct file reading with `auto_read()` function for `.gitignore` processing
- Applied same fix to `.whitelizard.txt` file reading
- `auto_read()` function automatically detects and handles UTF-8 BOM files, providing consistent file reading across the codebase
Verified successful file reading on both Windows and Ubuntu (WSL) environments with UTF-8 files both with and without BOM.
Also verified behavior when the file does not …
=> Fix file reading failure on non-UTF-8 Windows for BOM UTF-8 encoded whitelist and .gitignore files
