lizard.py
test/testOutput.py
test/test_options.py

Add an option to emit a warning if the line count if greater than a specified threshold.

Add a line count check

---

lizard.py
test/testCAndCPP.py

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/terryyin/lizard/72)

Add C/C++ structs as qualifiers

---

test/testCAndCPP.py

Relates to issue #70
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/terryyin/lizard/73)

C++ namespace alias failure

---

test/testCsharp.py

I know it is probably not that much help, but I hoped it would show we are keen for this feature. I took the example code from: https://msdn.microsoft.com/en-us/library/ms182212.aspx?cs-save-lang=1&cs-lang=csharp#code-snippet-1

Add C# test file #92

---

lizard.py
lizard_ext/lizardfans.py
test/testFans.py

@terryyin I think I fixed the given issues based on your feedback.
In the case of `stderr`, could you take a look it? hopefully, I understood what you meant by that comment.

Structural fan_in _fan_out modifications

---

lizard.py
lizard_ext/lizardns.py
lizard_languages/code_reader.py
test/testNestedStructures.py
theory.rst

The description of the metric is in Issue #69 and in the documentation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/terryyin/lizard/119)

Implement Nested Structure counting for C++

---

lizard.py
lizard_ext/lizardns.py
test/testNestedStructures.py

Revert "Generalize Nested Structure Counting for languages "

---

lizard_languages/clike.py

The 'nesting_level' is considered for internal uses only
and necessary for properly implementing
generic Nested Structures metric (PR #120).
The implementation is tested indirectly through the aforementioned metric.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/terryyin/lizard/123)

Implement C++ nesting_level for structures w/o braces

---

theory.rst

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/terryyin/lizard/127)

Clarify doc for nested function complexity count

---

test/test_languages/testCAndCPP.py

The initializer list is confused for a function definition.
Issue #118.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/terryyin/lizard/128)

Add tests for C++ init. list to function error

---

lizard_ext/lizardio.py

As @terryyin requested (another Pull Request) :
fixing average_caption of general_fan_out #133

general fan-out

---

theory.rst

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/terryyin/lizard/140)

Add documentation for IgnoreAssert extension

---

README.rst

This note documents some limitations of Lizard
and provides some contract for developers
to keep Lizard's code simpler.

Add a note of known limitations in code processing

---

.appveyor.yml

This adds minimal CI configurations for Appveyor-CI with Python 2.7.
Some tests on windows are erring with some filesystem issues:  https://ci.appveyor.com/project/rakhimov/lizard/build/1.0.1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/terryyin/lizard/159)

Add Appveyor CI configurations

---

.travis.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/terryyin/lizard/160)

PyPy and OS X on Travis CI

---

lizard.py

Possible solution for issue terryyin/lizard#164. :wink:

Visual Studio compatible output format

---

README.rst

- Put the logo at the top
(the website should be put on GitHub description)
- Remove some repetition
- Adjust badges (still needs Appveyor badge)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/terryyin/lizard/169)

Minor stylistic cleanup of readme

---

CHANGELOG.md
README.rst

The format is based on [Keep a Changelog](http://keepachangelog.com/).
This file is dedicated to track major changes for releases.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/terryyin/lizard/172)

Add a separate CHANGELOG

---

lizard_languages/clike.py
test/test_languages/testCAndCPP.py

Add C/C++ 'union' to full function qualification

---

lizard_ext/csvoutput.py
test/testOutputCSV.py

Signed-off-by: unknown <yalechen@yalechen-PC2.tencent.com>

change csv output.

---

README.rst

As requested, updated readme to include the other uses of lizard

Updated readme to include fastlane plugin

---

lizard_languages/java.py

fix bug: "operator" is not function in java

---

lizard_languages/__init__.py
lizard_languages/fortran.py
test/test_languages/testFortran.py

Hello,
I wanted to use [codemetrics](https://github.com/elmotec/codemetrics) hotspots on some Fortran projects.
So I added Fortran support to lizard along with unitests.
Would you be interested in officially adding this FortranReader?

Added Fortran support

---

lizard_languages/__init__.py
lizard_languages/kotlin.py
lizard_languages/swift.py
test/test_languages/testKotlin.py

Added kotlin support

---

lizard_languages/golike.py
test/test_languages/testGo.py

fix 2 bug
1. #304 
2. error function information when function return `interface{}`

Fix error function statistic in some scenario

---

README.rst

Related to #246.
Using `--prefix` works.

Fix install instruction

---

.github/workflows/python-app.yml
dev_requirements.txt

add github actions

---

lizard_languages/__init__.py
lizard_languages/solidity.py
test/testLanguages.py
test/test_languages/testSolidity.py

added Solidity support

---

lizard.py
lizard_languages/__init__.py
lizard_languages/erlang.py
test/testLanguages.py
test/test_languages/testErlang.py

https://www.erlang.org/
Hello we use Lizard in our university project and i wanted to add erlang support and it was easiest to add it directly here :) its probly not best and fastest implementation but i think it should work quite good, if my code doesn't meet your requirements i will be happy to fix it :)

added Erlang support

---

lizard.py

chore: Remove unused function_stack property

---

lizard_languages/__init__.py
lizard_languages/clike.py
lizard_languages/fortran.py
lizard_languages/python.py
lizard_languages/zig.py
pylintrc
setup.cfg
test/testLanguages.py
test/test_languages/testZig.py

Hi, I wanted to use lizard for my master thesis project, but needed also the support for zig language. I added it here, seems to work. If you let me know that there is something wrong, I can try to fix it.
Side note: in 8f3742c28c9fd5d86fe6adfd906c9c91531390e4 I had to fix some pylint/pycodestyle formatting issues or otherwise `build.sh` would fail on style check. I guess that we just have different versions of pylint/pycodestyle and that's why it failed, but I couldn't find the correct version (`dev_requirements.txt` does not contain versions). I can revert these changes if you'd like.

Support for zig language
